AWSTemplateFormatVersion: 2010-09-09
Resources:
  JingyiWangNotesReactDeployBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
  Distribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - # Use the DeployBucket as the CDN origin
            DomainName: !GetAtt JingyiWangNotesReactDeployBucket.DomainName
            Id: !Ref JingyiWangNotesReactDeployBucket
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultRootObject: index.html
        Enabled: true
        # Configure the caching behavior for our CDN
        DefaultCacheBehavior:
          MinTTL: 86400  # 1 day
          MaxTTL: 31536000  # 1 year
          ForwardedValues:
            QueryString: true
          TargetOriginId: !Ref JingyiWangNotesReactDeployBucket
          ViewerProtocolPolicy: "allow-all"